# Generated by Django 5.1.2 on 2025-07-19 15:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_description', models.CharField(blank=True, max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage_return', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.CharField(max_length=100)),
                ('duration_span', models.CharField(blank=True, choices=[('hour(s)', 'Hour(s)'), ('day(s)', 'Day(s)'), ('week(s)', 'Week(s)'), ('month(s)', 'Month(s)'), ('year(s)', 'Year(s)')], max_length=20, null=True)),
                ('time_rate', models.CharField(choices=[('none', 'None'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('network', models.CharField(choices=[('BTC', 'BTC'), ('ERC20', 'ERC20'), ('DOT', 'DOT'), ('BEP2', 'BEP2'), ('BEP20', 'BEP20'), ('ERC20', 'ERC20'), ('OMNI', 'OMNI'), ('TRC20', 'TRC20')], max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('wallet_address', models.CharField(max_length=255, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='wallet_qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='RawPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=50)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_img/')),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('referred_users', models.ManyToManyField(blank=True, related_name='referrers', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('bank_country', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('routing_number', models.CharField(max_length=100)),
                ('swift_code', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('united states dollar', 'United States Dollar'), ('euro', 'Euro'), ('british pound', 'British Pound'), ('japanese yen', 'Japanese Yen'), ('canadian dollar', 'Canadian Dollar'), ('australian dollar', 'Australian Dollar'), ('swiss franc', 'Swiss Franc'), ('chinese yuan', 'Chinese Yuan'), ('swedish krona', 'Swedish Krona'), ('new zealand dollar', 'New Zealand Dollar'), ('mexican peso', 'Mexican Peso'), ('singapore dollar', 'Singapore Dollar'), ('hong kong dollar', 'Hong Kong Dollar'), ('norwegian krone', 'Norwegian Krone'), ('south korean won', 'South Korean Won'), ('russian ruble', 'Russian Ruble'), ('indian rupee', 'Indian Rupee'), ('brazilian real', 'Brazilian Real'), ('south african rand', 'South African Rand'), ('turkish lira', 'Turkish Lira')], max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_card_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=50)),
                ('name_on_card', models.CharField(max_length=50)),
                ('expiration_date', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=100)),
                ('city_town', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cashout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_id', models.CharField(blank=True, max_length=16, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisableAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentIntrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYCverification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('proof_selfie', models.ImageField(upload_to='kyc/')),
                ('font_side', models.ImageField(upload_to='kyc/')),
                ('back_side', models.ImageField(upload_to='kyc/')),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_proof', models.ImageField(upload_to='deposit_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('successful', 'Successful')], default='pending', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('return_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_intrest_return', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_intrest_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment', models.IntegerField(default=0)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('successful', 'Successful')], default='pending', max_length=10)),
                ('investment_status', models.CharField(choices=[('awaiting', 'Awaiting'), ('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='awaiting', max_length=20)),
                ('investment_begins', models.DateTimeField(blank=True, null=True)),
                ('investment_ends', models.DateTimeField(blank=True, null=True)),
                ('investment_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=10)),
                ('investment_time_rate', models.CharField(max_length=10)),
                ('last_update_time', models.DateTimeField(blank=True, null=True)),
                ('cashout', models.BooleanField(default=False)),
                ('withdrawn', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance_deducted', models.BooleanField(default=False)),
                ('investment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.investmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('referral_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersCommissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerifiactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.ImageField(upload_to='profile_img/')),
                ('address', models.CharField(max_length=50)),
                ('city_town', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=20)),
                ('ssn', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('walletAddress', models.CharField(max_length=100)),
                ('coin', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('tether', 'Tether'), ('litecoin', 'Litecoin'), ('ripple', 'Ripple'), ('cardano', 'Cardano'), ('dogecoin', 'Dogecoin'), ('stellar', 'Stellar')], max_length=100)),
                ('network', models.CharField(choices=[('BEP2', 'BEP2'), ('BEP20', 'BEP20'), ('ERC20', 'ERC20'), ('OMNI', 'OMNI'), ('TRC20', 'TRC20')], max_length=100)),
                ('wallet_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method_id', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('successful', 'Successful')], max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
